### ISSUE TITLE
Ability to exclude SObject field

### ISSUE THREAD

**Issue by nebc-jasonfung** [aidan-harding/nebula-object-transformer#8]
**Scenario 1:**

Round trip `SF -> 3rd party system -> SF` we transform an SObject which includes a formula field. On the reverse transformation where a round trip SObject is used to update the same record, it fails. This is because the formula field is included as part of the reverse transformation query.

**Scenario 2:**
From `3rd party system -> SF (Account)`. Account Transformation will more often than not include the 'Name' field, as this is required. If the response requires a `PersonAccount` to be created, the 'Name' field is not editable, therefore the DML will fail.

**Workarounds:**

_Clunky_
1.) Transform your response as normal to the relevant SObject type. Serialize and deserialize to Map<String, Object>. Remove the SObject field from the map. Serialize and deserialize back to the SObject type. Complete DML as normal.

_Repetitive_
2.) Create a separate Transformation CMDT and copy all the updatable fields.

**Comment by aidan-harding** [comment]
Hi @nebc-jasonfung,

I'm trying to decide how best to do this...

1. It could be done by having two new checkboxes on the `Transformation_Field__mdt` record: Source_Read_Only__c and Target_Read_Only__c. Then, would make a new instance of `Transformation` (or `ReverseTransformation`), it could filter out fields that are read-only on the target (for reversing, the source). I'm preferring this at the moment.

2. Alternatively, we could have an extra method on the `Transformation` class itself to let you pass in a `BooleanFunction` that filters the fields. That would provide more flexibility in the filtering

I think that I prefer 1 because then the CMDT records tell you exactly what's going to happen. But I'm interested to hear your thoughts.

Also, note that we made the constructor that takes `List<Transformation_Field__mdt>` global so there's a third workaround now of querying the CMDT and filtering yourself, but I think it's still worth adding something to the library to make this more straightforward and consistent.

**Comment by DanBeerNebula** [comment]
I did wonder if we can do something with the DescribeFieldResult from the field that is being written to. If the record Id is populated then clearly it's not a new record - but that would require passing in the existing record into the transformation.

With your options, I'd go with 1 for now, and then see if any requirement comes in to implement the BooleanFunction as an additional filter if required.

**Comment by nebc-jasonfung** [comment]
Hi @aidan-harding 

My initial thought when writing up this issue was to resolve this with a new checkbox value, I hadn't considered your 2nd point and even @DanBeerNebula idea of using DescribeFieldResult.

With that, I agree that point 1 is the cleanest solution. Anyone creating a new Transformation field will see and be aware that a scenario like this issue could happen vs the BooleanFunction where only if you're conscious that it exists, then you will use it, similar to how some test record source functions are missed despite them actually being available in the library, although more forgiving in a test record source sense.

**Comment by aidan-harding** [comment]
Checkbox it is, then!

Transformation Field already has many fields, but this one seems worth it. 

To Dan's suggestion of using DescribeResult, it's not that simple because the transformer transforms anything, not just SObjects. So it can't reliably check the field properties.
